voxowl/particubes

lua-docs/content/reference/Block.md, lua-docs/content/reference/Enum.md, lua-docs/content/reference/Event.md, lua-docs/content/reference/EventType.md, lua-docs/content/reference/GlobalEnvironment.md, lua-docs/content/reference/Local.md, lua-docs/content/reference/Number3.md, lua-docs/content/reference/Player.md, lua-docs/content/reference/PlayerMode.md, lua-docs/content/reference/Server.md, lua-docs/content/reference/Tick.md, lua-docs/content/reference/index.md
add missing fields and descriptions
=> update Lua doc

lua-docs/content/reference/Block.md
- Block: add doc for Block.New(id, x, y, z)
=> update docs - Block

lua-docs/content/_templates/default.tmpl, lua-docs/content/reference/Import.md, lua-docs/content/reference/index.md
=> add “Import” in sandbox reference

lua-docs/content/reference/Resources.md, lua-docs/content/reference/index.md
=> add docs page for Resources/R

game-scripts/default.lua, game-scripts/default_modified.lua
- update default script with coloring the ground when holding the frying pan
- add new default script variant with auto fire
=> update default script

lua-docs/content/reference/fog.yml
=> Lua doc : small update of the Fog reference

lua-docs/content/reference/label.yml
=> Add arguments to Label Add function

lua-docs/content/reference/timecyclemark.yml
=> Fix type and Color.Red

lua-docs/content/reference/player.yml
=> Add Impact return type for Player:CastRay

lua-docs/content/reference/mutableshape.yml, lua-docs/content/reference/shape.yml
fixes https://github.com/voxowl/particubes-private/issues/1545
=> docs : nil air blocks

lua-docs/content/reference/shape.yml
=> Lua Shape: update description for Anchor

lua-docs/content/reference/button.yml, lua-docs/content/reference/timecycle.yml, lua-docs/content/reference/timecyclemark.yml
`TimeCycleMark`s are now automatically added to `TimeCycle.Marks`
=> Remove table.insert for TimeCycle.Marks

lua-docs/content/page.tmpl, lua-docs/content/reference/block.yml, lua-docs/content/reference/client.yml, lua-docs/content/reference/mutableshape.yml, lua-docs/content/style/css/style.css, lua-docs/go/src/website/page.go
Adds support for different sets of function arguments:
Plus small documentation content improvements.
⚠️ do not merge before 0.0.20 is available
=> Documentation updates

lua-docs/content/reference/config.yml, lua-docs/content/reference/object.yml
Documents:
- Config.ConstantAcceleration
- Object.Acceleration
- more details about ObjectMotion
⚠️ do not merge before 0.0.20 is available
=> Docs: Config.ConstantAcceleration & Object.Acceleration

lua-docs/content/reference/array.yml, lua-docs/content/reference/block.yml, lua-docs/content/reference/boolean.yml, lua-docs/content/reference/function.yml, lua-docs/content/reference/impact.yml, lua-docs/content/reference/index.yml, lua-docs/content/reference/integer.yml, lua-docs/content/reference/mutableshape.yml, lua-docs/content/reference/number.yml, lua-docs/content/reference/object.yml, lua-docs/content/reference/shape.yml, lua-docs/content/reference/string.yml, lua-docs/content/reference/table.yml, lua-docs/content/reference/time.yml
Add `integer` type and other fixes.
=> Add integer type

game-localization/localization_en.txt, game-localization/localization_fr.txt
- EN (English) ⚙️ 
- FR (Français) 
- ...
=> add game localization files

game-localization/localization_ru.txt
Russian translation: No mistakes this time
=> Russian translation v3

localization/localization_sq.txt
=> add localization for Albanian language

game-localization/localization_it.txt
=> Added Italian translation

lua-docs/content/reference/otherplayers.yml, lua-docs/content/reference/players.yml
=> update doc : Players

lua-scripts/README.md, lua-scripts/basic_multiplayer.lua
Adding basic multiplayer script to `/lua-scripts`.
=> basic multiplayer script

lua-docs/content/reference/index.yml, lua-docs/content/reference/screen.yml
Screen has been available for a little while, but we forgot to document it... 🤦‍♂️
=> Lua docs: add Screen

lua-docs/content/reference/client.yml
fixes https://github.com/voxowl/particubes-private/issues/2724
=> Docs : remove “Inputs” type

lua-docs/content/guides/index.yml, lua-docs/content/guides/snippets/collisions-triggers.yml, lua-docs/content/guides/snippets/setup-scene.yml, lua-docs/content/guides/snippets/ui.yml, lua-docs/content/guides/snippets/user-actions.yml, lua-docs/content/guides/tutorials/tutoworld.yml, lua-docs/content/images/guides/01-tutoworld_crate-no-collision.jpg, lua-docs/content/images/guides/01-tutoworld_instantiate-crate.jpg, lua-docs/content/images/guides/01-tutoworld_instantiate-crates.jpg, lua-docs/content/images/guides/01-tutoworld_raycast.jpg, lua-docs/content/images/guides/01-tutoworld_score-label.jpg, lua-docs/content/images/guides/01-tutoworld_weapon.jpg, lua-docs/content/images/guides/code-publish.jpg, lua-docs/content/images/guides/create-screen_sections.jpg, lua-docs/content/images/guides/edit-screen_world.jpg, lua-docs/content/images/guides/main-screen_build.jpg, lua-docs/content/media/guides/01-tutoworld_collision.mp4, lua-docs/content/media/guides/01-tutoworld_demo.mp4, lua-docs/content/media/guides/01-tutoworld_gem.mp4, lua-docs/content/media/guides/01-tutoworld_initworld.mp4, lua-docs/content/media/guides/01-tutoworld_map.mp4, lua-docs/content/media/guides/01-tutoworld_swingright.mp4, lua-docs/content/page.tmpl, lua-docs/content/style/css/style.css, lua-docs/go/src/website/main.go, lua-docs/go/src/website/page.go
Update the guides sections with:
- some step-by-step tutorials
- handy Lua snippets for easier templating
=> Update docs Guides section

lua-docs/content/guides/index.yml, lua-docs/content/guides/quick/testing-multiplayer-game.yml, lua-docs/content/guides/tutorials/lone-scoundrel.yml, lua-docs/content/guides/tutorials/space-race.yml, lua-docs/content/guides/tutorials/tutoworld.yml, lua-docs/content/images/guides/03-space-race_lifecycle.jpg, lua-docs/content/images/guides/server-client_00.jpg, lua-docs/content/images/guides/server-client_01.jpg, lua-docs/content/images/guides/server-client_02.jpg, lua-docs/content/images/guides/server-client_03.jpg, lua-docs/content/images/guides/server-client_04.jpg, lua-docs/content/images/guides/server-client_05.jpg, lua-docs/content/images/guides/server-client_06.jpg, lua-docs/content/images/test-multiplayer_list-servers.png, lua-docs/content/images/test-multiplayer_pick-server.png, lua-docs/content/media/guides/01-tutoworld_swingright.mp4, lua-docs/content/media/guides/03-space-race_demo-final.mp4, lua-docs/content/media/guides/03-space-race_demo-solo.mp4, lua-docs/content/media/guides/03-space-race_spawn-players.mp4, lua-docs/content/media/guides/03-space-race_sync.mp4, lua-docs/go/src/website/page.go
Add Tutoral n°3: Space Race - solo to multiplayer game transformation.
=> Add guide for multiplayer game

lua-docs/content/guides/tutorials/tutoworld.yml
Do a few fixes in the Tutoworld guide, as listed in this issue: https://github.com/voxowl/particubes-private/issues/3284.
(Note: it also fixes the indirectly referenced issue here: https://github.com/cubzh/cubzh/issues/6 )
=> Fixes in Tutoworld guide

localization/localization_nl.txt
=> I translated for dutch
